name: Manually Deploy to heroku

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.8.9 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          region: "eu"
          usedocker: true
          docker_heroku_process_type: worker
        env:
          HD_CREDENTIALS: ${{secrets.CREDENTIALS}}
          HD_CLIENT_SECRET: ${{secrets.CLIENT_SECRET}}
          HD_CONSTANTS_URL: ${{secrets.CONSTANTS_URL}}
          HD_MAX_CONCURRENT_DOWNLOADS: ${{secrets.MAX_CONCURRENT_DOWNLOADS}}
          HD_GIT_TOKEN: ${{secrets.GIT_TOKEN}}
          HD_GIT_USER: ${{secrets.GIT_USER}}
          HD_GIT_REPO: ${{secrets.GIT_REPO}}
          HD_HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
          HD_HEROKU_APP_NAME: ${{secrets.HEROKU_APP_NAME}} 